### ISSUE TITLE
No module named 'core'

### ISSUE THREAD

**Issue by danny851103** [Nadavc220/SemanticSegmentationInArtPaintings#8]
Hello, when i trying to run the script `python gram_embedding/emmbed_train_set.py`
it shows the following error

**Traceback (most recent call last):
  File "gram_embedding/emmbed_train_set.py", line 7, in <module>
    from core.datasets.dataset_path_catalog import DatasetCatalog
ModuleNotFoundError: No module named 'core'**

i tried `pip install tensorflow_datasets`
and tried to add `from .core import *`
but it's all not working, please help

**Comment by Nadavc220** [comment]
seems like you PYTHONPATH environment variable may not be pointing to the source directory.
try running "set PYTHONPATH=<path to source dir>".

**Comment by danny851103** [comment]
Hi. thanks  for your reply, it's work!
But now i have an other issue while running `python gram_embedding/emmbed_train_set.py`
```php
Traceback (most recent call last):
  File "gram_embedding/emmbed_train_set.py", line 30, in <module>
    dataloader = DatasetCatalog.get(dataset, data_split, transform=trans)
  File "C:\Users\admin\Desktop\SemanticSegmentationInArtPaintings-main\core\datasets\dataset_path_catalog.py", line 192, in get
    return DramDataSet(args["root"], args["movement"], max_iters=max_iters, num_classes=num_classes, split=mode, transform=transform)
  File "C:\Users\admin\Desktop\SemanticSegmentationInArtPaintings-main\core\datasets\dram.py", line 26, in __init__
    with open(data_list_path, "r") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '../data/DRAM_500\\train\\realism.txt'
```
I use anaconda virtual env in windows system, 
and i do follow your step rename folder from DRAM_processed to DRAM_500
I can see there's something wrong with my path, but i don't know where to fix it.
Please help.

**Comment by Nadavc220** [comment]
You path seems like a mix between the path formats of windows and linux. Change the '/' to '\\' or the other way around.

**Comment by danny851103** [comment]
I try to change all '/' and '\\\\' to '\\' by editing `DATASET_DIR = "..\data\"` in **dataset_path_catalog.py**
but there's an error
```php
Traceback (most recent call last):
  File "gram_embedding/emmbed_train_set.py", line 7, in <module>
    from core.datasets.dataset_path_catalog import DatasetCatalog
  File "C:\Users\admin\Desktop\SemanticSegmentationInArtPaintings-main\core\datasets\__init__.py", line 1, in <module>
    from .build import build_dataset, build_dataset_no_cfg, build_transform, build_inference_transform
  File "C:\Users\admin\Desktop\SemanticSegmentationInArtPaintings-main\core\datasets\build.py", line 2, in <module>
    from .dataset_path_catalog import DatasetCatalog
  File "C:\Users\admin\Desktop\SemanticSegmentationInArtPaintings-main\core\datasets\dataset_path_catalog.py", line 8
    DATASET_DIR = "..\data\"
                           ^
SyntaxError: EOL while scanning string literal
```
seems like python don't let me to use '\\'  at the end of a string
so i change to '\\\\' `DATASET_DIR = "..\\data\\"`
but it still not working
```php
Traceback (most recent call last):
  File "gram_embedding/emmbed_train_set.py", line 30, in <module>
    dataloader = DatasetCatalog.get(dataset, data_split, transform=trans)
  File "C:\Users\admin\Desktop\SemanticSegmentationInArtPaintings-main\core\datasets\dataset_path_catalog.py", line 192, in get
    return DramDataSet(args["root"], args["movement"], max_iters=max_iters, num_classes=num_classes, split=mode, transform=transform)
  File "C:\Users\admin\Desktop\SemanticSegmentationInArtPaintings-main\core\datasets\dram.py", line 26, in __init__
    with open(data_list_path, "r") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '..\\data\\DRAM_500\\train\\realism.txt'
```
I'm confused, pls help

**Comment by Nadavc220** [comment]
it's seems you are using windows, so try replacing all slashes with "\\". Anyway, you can use the os library to see how paths are represented in your system.

**Comment by danny851103** [comment]
Hi, I solved the path problem, but when i running PCA, i get some memory issue.
```php
Loaded DRAM realism train set with 1074 images
Loaded DRAM impressionism train set with 1538 images
Loaded DRAM post_impressionism train set with 1462 images
Loaded DRAM expressionism train set with 1603 images
Encoding 1074 source images...
Encoding 1538 source images...
Encoding 1462 source images...
Encoding 1603 source images...
Running PCA on data...
Traceback (most recent call last):
  File "gram_embedding/emmbed_train_set.py", line 78, in <module>
    torch.save(pca, os.path.join(OUTPUT_DIR, 'pca_f'), pickle_protocol=2)
  File "C:\Users\admin\anaconda3\envs\GPU_python38\lib\site-packages\torch\serialization.py", line 629, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "C:\Users\admin\anaconda3\envs\GPU_python38\lib\site-packages\torch\serialization.py", line 841, in _save
    pickler.dump(obj)
MemoryError
```
One of the solutions I've found is to use joblib instead of pickle,
but i don't know how to change `torch.save(pca, os.path.join(OUTPUT_DIR, 'pca_f'), pickle_protocol=4)` to use joblib
Or is there another solution?
If it's just because I don't have enough memory, could you tell me how much memory i need to do Inference.
